version: "3.8"

services:
  # db:
  #   image: postgres:15.1
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - 5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   restart: on-failure
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/
  #   networks:
  #     - kbtg-assign

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "2565:2565"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    networks:
      - kbtg-assign

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "2565:2565"
    

networks:
  kbtg-assign:
    driver: bridge
    