FROM golang:1.19.3-alpine

WORKDIR /go/src/github.com/hirasawaau/assessment

ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable

COPY go.* ./
COPY *.go ./
COPY src ./src

RUN go mod download

CMD CGO_ENABLED=0 go test --tags=integration ./...

