name: Test

on:
  pull_request:
    types:
      - "opened"
      

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  # build:
  #   name: build
  #   runs-on: ubuntu-20.04
    
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19
      
  #     - name: Prepair GHCR
  #       run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
      
  #     - name: Build
  #       run: docker build -t ghcr.io/${{ secrets.GHCR_USER }}/assessment:latest .
      
  #     - name: Push
  #       run: docker push ghcr.io/${{ secrets.GHCR_USER }}/assessment:latest

  integration_test:
    name: integration_test
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Clean image
        run: docker compose down
      - name: Build image
        run: docker compose up --build -d
      - name: Test
        run: go run test -v --tags=integration ./...
        
  unit_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install Module
        run: go mod download
      - name: Test
        run: go run test -v --tags=unit ./...