name: Test

on:
  pull_request:
    types:
      - "opened"
      

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  integration_test:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Clean image
        run: docker compose -f docker-compose.test.yml down
      - name: Test
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app-test
        
  unit_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install Module
        run: go mod download
      - name: Test
        run: go run test -v --tags=unit ./...